name: logistic
description: Storeware Logistics

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.21.09+22

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get:  ^4.3.8
  
  controls_web:
    path : ../../flutter_dart/controls_web  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2 
  #flutter_gen_runner:  

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
